"""Add libre_mode to users table

Revision ID: 0002
Revises: 0001
Create Date: 2025-08-07 12:30:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0002'
down_revision = '0001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('libre_mode', sa.Boolean(), nullable=True))
    
    # Set default value for existing users
    op.execute("UPDATE users SET libre_mode = false WHERE libre_mode IS NULL")
    
    # Make column non-nullable after setting default
    op.alter_column('users', 'libre_mode', nullable=False, server_default='false')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'libre_mode')
    # ### end Alembic commands ###