"""Add unique constraint for user progress

Revision ID: 0003
Revises: 0002
Create Date: 2025-08-07 14:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0003'
down_revision = '0002'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add unique constraint to prevent duplicate progress records
    op.create_unique_constraint(
        'unique_user_day_progress', 
        'user_progress', 
        ['user_id', 'day']
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_user_day_progress', 'user_progress', type_='unique')
    # ### end Alembic commands ###